Algoritmo "Saudacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Introdução às funcionalidades e sintaxe da linguagem
// Autor(a)    : Gunnar
// Data atual  : 18/06/2024
Var
// Seção de Declarações das variáveis 
     msg:caractere

Inicio
      msg <- "Ola, mundo!"
      Escreval("Mensagem ",msg)
      Escreva("Me livrei da maldição.")

Fimalgoritmo